[package]
name = "watso/animal-rescue-simulator"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Loader = "sleitnick/loader@2.0.0"
Trove = "sleitnick/trove@1.3.0"
Concur = "sleitnick/concur@0.1.2"
Net = "sleitnick/net@0.2.0"
WaitFor = "sleitnick/wait-for@1.0.0"
Input = "sleitnick/input@2.3.0"
Replica = "luarook/replica@0.4.5"
ProfileService = "howmanysmall/typed-profile-service@1.0.3"
React = "jsdotlua/react@17.1.0"